version: '3.8'

services:
  flash-reading:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: flash-reading
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf